from enum import StrEnum


class AuditAction(StrEnum):
    INGESTION_CREATED = "INGESTION_CREATED"
    INGESTION_READ = "INGESTION_READ"
    INGESTION_FAILED = "INGESTION_FAILED"

    CLASSIFICATION_APPLIED = "CLASSIFICATION_APPLIED"
    CLASSIFICATION_CREATED = "classification_created"

    DATA_DELETED = "DATA_DELETED"
    DATA_EXPORTED = "DATA_EXPORTED"
